### ISSUE TITLE
(non-urgent) twrp 3.0.0-1 has been released but twrp ui and the splash screen show 3.0.0-0

### ISSUE THREAD

**Issue by ghost** [TeamWin/android_device_oneplus_oneplus2#4]
twrp 3.0.0-1 has been released
however, twrp says 3.0.0-0 even after updating
this issue is not very urgent and does not need to be fixed asap but it may cause confusion to the users

**Comment by Dees-Troy** [comment]
Our Jenkins build script wasn't properly replacing the version number which I have now corrected.
