### ISSUE TITLE
No support for android 6.0 firmware 

### ISSUE THREAD

**Issue by ghost** [TeamWin/android_device_oneplus_oneplus2#5]
The kernel sources for marshmallow kernel are out but twrp hasn't been updated yet to support the new firmware

**Comment by jfeise** [comment]
I have build an unofficial version of TWRP 3.0.2-0, using the CM tree, that works with the new firmware in the official CM 13 nightlies: https://www.feise.com/~jfeise/Downloads/twrp-3.0.2-0-unofficial-20160610-oneplus2.img
MD5: 776907ebd38a879ab2dcf5ad5c69bd19

**Comment by jfeise** [comment]
There is a TWRP 3.0.2-1 out for the OP2. While it works with the official CM nightlies, decryption doesn't work.
